languague: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t canozunal/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true canozunal/docker-react npm run test